# Generated by Django 6.0.1 on 2026-01-10 18:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.TextField(help_text='Full path to the file')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('code', 'Code'), ('pdf', 'PDF Document'), ('doc', 'Document'), ('txt', 'Text File'), ('md', 'Markdown'), ('json', 'JSON'), ('yaml', 'YAML'), ('xml', 'XML'), ('image', 'Image'), ('other', 'Other')], max_length=50)),
                ('file_extension', models.CharField(blank=True, max_length=10)),
                ('content', models.TextField(blank=True, help_text='File content', null=True)),
                ('content_hash', models.CharField(blank=True, help_text='SHA-256 hash for deduplication', max_length=64)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('java', 'Java'), ('cpp', 'C++'), ('csharp', 'C#'), ('go', 'Go'), ('rust', 'Rust'), ('php', 'PHP'), ('ruby', 'Ruby'), ('swift', 'Swift'), ('kotlin', 'Kotlin'), ('sql', 'SQL'), ('html', 'HTML'), ('css', 'CSS'), ('other', 'Other')], help_text='Programming language for code files', max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_indexed', models.BooleanField(default=False)),
                ('embedding_id', models.CharField(blank=True, help_text='Reference to Pinecone vector ID', max_length=255, null=True)),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='context.contextfile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_files', to='projects.project')),
            ],
            options={
                'db_table': 'context_files',
                'ordering': ['file_path'],
            },
        ),
        migrations.CreateModel(
            name='CodeAnalysis',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('functions', models.JSONField(default=list, help_text='List of functions found')),
                ('classes', models.JSONField(default=list, help_text='List of classes found')),
                ('imports', models.JSONField(default=list, help_text='List of imports/dependencies')),
                ('exports', models.JSONField(default=list, help_text='List of exports')),
                ('lines_of_code', models.IntegerField(default=0)),
                ('complexity_score', models.FloatField(blank=True, null=True)),
                ('dependencies', models.JSONField(default=list, help_text='List of file dependencies')),
                ('dependent_files', models.JSONField(default=list, help_text='List of files that depend on this file')),
                ('analyzer_version', models.CharField(blank=True, max_length=50)),
                ('analysis_date', models.DateTimeField(auto_now=True)),
                ('context_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='context.contextfile')),
            ],
            options={
                'verbose_name_plural': 'Code analyses',
                'db_table': 'code_analysis',
            },
        ),
        migrations.CreateModel(
            name='FileIndex',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField(default=0, help_text='Chunk number for large files')),
                ('content_chunk', models.TextField(help_text='Text chunk for searching')),
                ('start_line', models.IntegerField(blank=True, null=True)),
                ('end_line', models.IntegerField(blank=True, null=True)),
                ('chunk_metadata', models.JSONField(default=dict)),
                ('context_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indices', to='context.contextfile')),
            ],
            options={
                'db_table': 'file_indices',
                'ordering': ['context_file', 'chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='contextfile',
            index=models.Index(fields=['project'], name='context_fil_project_67ed20_idx'),
        ),
        migrations.AddIndex(
            model_name='contextfile',
            index=models.Index(fields=['file_type'], name='context_fil_file_ty_c97edf_idx'),
        ),
        migrations.AddIndex(
            model_name='contextfile',
            index=models.Index(fields=['is_indexed'], name='context_fil_is_inde_b503e2_idx'),
        ),
        migrations.AddIndex(
            model_name='contextfile',
            index=models.Index(fields=['content_hash'], name='context_fil_content_d94b64_idx'),
        ),
        migrations.AddIndex(
            model_name='contextfile',
            index=models.Index(fields=['parent_folder'], name='context_fil_parent__ccf0c8_idx'),
        ),
        migrations.AddIndex(
            model_name='fileindex',
            index=models.Index(fields=['context_file', 'chunk_index'], name='file_indice_context_12c985_idx'),
        ),
    ]
