# Generated by Django 6.0.1 on 2026-01-10 18:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorySnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('snapshot_name', models.CharField(max_length=255)),
                ('short_term_data', models.JSONField(default=dict)),
                ('long_term_data', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_snapshots', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'memory_snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LongTermMemory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('memory_key', models.CharField(max_length=255)),
                ('content', models.JSONField(help_text='Memory content as JSON')),
                ('memory_category', models.CharField(blank=True, choices=[('architectural_decision', 'Architectural Decision'), ('user_preference', 'User Preference'), ('constraint', 'Constraint'), ('pattern', 'Pattern'), ('mistake', 'Mistake'), ('best_practice', 'Best Practice'), ('lesson_learned', 'Lesson Learned')], max_length=100, null=True)),
                ('importance_score', models.FloatField(default=0.5, help_text='Importance score from 0 to 1')),
                ('access_count', models.IntegerField(default=0, help_text='Number of times this memory has been accessed')),
                ('embedding_id', models.CharField(blank=True, help_text='Reference to Pinecone vector ID', max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_accessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='long_term_memories', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='long_term_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'long_term_memory',
                'ordering': ['-importance_score', '-created_at'],
                'indexes': [models.Index(fields=['user'], name='long_term_m_user_id_4dd469_idx'), models.Index(fields=['project'], name='long_term_m_project_ff91b6_idx'), models.Index(fields=['memory_category'], name='long_term_m_memory__35aa56_idx'), models.Index(fields=['-importance_score'], name='long_term_m_importa_19f2e4_idx'), models.Index(fields=['memory_key'], name='long_term_m_memory__e8d98b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShortTermMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(help_text='Reference to chat session or execution session')),
                ('memory_key', models.CharField(max_length=255)),
                ('content', models.JSONField(help_text='Memory content as JSON')),
                ('memory_type', models.CharField(choices=[('conversation', 'Conversation'), ('code_snippet', 'Code Snippet'), ('decision', 'Decision'), ('context', 'Context'), ('state', 'State')], default='conversation', max_length=50)),
                ('ttl_seconds', models.IntegerField(default=3600, help_text='Time to live in seconds (default: 1 hour)')),
                ('expires_at', models.DateTimeField(help_text='Automatically set based on TTL')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_term_memories', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_term_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'short_term_memory',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='short_term__user_id_bac390_idx'), models.Index(fields=['project'], name='short_term__project_f87dc3_idx'), models.Index(fields=['session_id'], name='short_term__session_938ce3_idx'), models.Index(fields=['expires_at'], name='short_term__expires_15da9e_idx'), models.Index(fields=['memory_key'], name='short_term__memory__a8118e_idx')],
            },
        ),
    ]
