# Generated by Django 6.0.1 on 2026-01-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentexecution_user_agentsession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentexecution',
            name='agent_type',
            field=models.CharField(default='general', help_text='Type of agent: planner, executor, retriever, reviewer', max_length=100),
        ),
    ]
