# Generated by Django 6.0.1 on 2026-01-10 18:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='not_started', max_length=50)),
                ('depth_level', models.IntegerField(default=0, help_text='0 = root feature, 1 = sub-feature, etc.')),
                ('order_index', models.IntegerField(default=0, help_text='Order within siblings')),
                ('priority', models.IntegerField(default=0, help_text='Higher number = higher priority')),
                ('estimated_effort', models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra_large', 'Extra Large')], max_length=50, null=True)),
                ('actual_effort_minutes', models.IntegerField(blank=True, help_text='Actual time spent in minutes', null=True)),
                ('dependencies', models.JSONField(default=list, help_text='Array of feature IDs this depends on')),
                ('blocking_reason', models.TextField(blank=True)),
                ('related_files', models.JSONField(default=list, help_text='Array of file IDs')),
                ('related_memories', models.JSONField(default=list, help_text='Array of memory IDs')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='planning.feature')),
            ],
            options={
                'db_table': 'features',
                'ordering': ['plan', '-priority', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_version', models.IntegerField(default=1)),
                ('tree_structure', models.JSONField(default=dict, help_text='Full hierarchical structure for quick access')),
                ('total_features', models.IntegerField(default=0)),
                ('completed_features', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('active_feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_in_plan', to='planning.feature')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='projects.project')),
            ],
            options={
                'db_table': 'project_plans',
            },
        ),
        migrations.AddField(
            model_name='feature',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='planning.projectplan'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(blank=True, choices=[('code_generation', 'Code Generation'), ('code_modification', 'Code Modification'), ('research', 'Research'), ('review', 'Review'), ('testing', 'Testing'), ('documentation', 'Documentation')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=50)),
                ('order_index', models.IntegerField(default=0)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('execution_time_seconds', models.IntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='planning.feature')),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['feature', 'order_index'],
            },
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['plan'], name='features_plan_id_f9642c_idx'),
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['parent'], name='features_parent__d92639_idx'),
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['status'], name='features_status_b4cdda_idx'),
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['-priority'], name='features_priorit_34431e_idx'),
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['order_index'], name='features_order_i_3ae622_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['feature'], name='tasks_feature_30b463_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='tasks_status_031d4c_idx'),
        ),
    ]
