# Generated by Django 6.0.1 on 2026-01-10 20:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('code', 'Code'), ('documentation', 'Documentation'), ('conversation', 'Conversation'), ('memory', 'Memory'), ('planning', 'Planning')], max_length=50)),
                ('source_id', models.CharField(blank=True, help_text='ID of the source document (context_file_id, conversation_id, etc.)', max_length=255)),
                ('content', models.TextField(help_text='The text content that was embedded')),
                ('chunk_index', models.IntegerField(default=0, help_text='Chunk number for large documents')),
                ('pinecone_id', models.CharField(help_text='Pinecone vector ID', max_length=255, unique=True)),
                ('namespace', models.CharField(blank=True, help_text='Pinecone namespace for isolation', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('token_count', models.IntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='projects.project')),
            ],
            options={
                'db_table': 'embedding_documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'document_type'], name='embedding_d_project_f0976c_idx'), models.Index(fields=['pinecone_id'], name='embedding_d_pinecon_9ab8b4_idx'), models.Index(fields=['source_id'], name='embedding_d_source__7c0995_idx')],
            },
        ),
        migrations.CreateModel(
            name='SemanticSearchLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField(help_text='The search query text')),
                ('top_k', models.IntegerField(default=5)),
                ('result_count', models.IntegerField(default=0)),
                ('result_ids', models.JSONField(default=list, help_text='List of returned embedding IDs')),
                ('scores', models.JSONField(default=list, help_text='Similarity scores')),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('namespace', models.CharField(blank=True, max_length=255)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_logs', to='projects.project')),
            ],
            options={
                'db_table': 'semantic_search_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='semantic_se_project_563ecc_idx')],
            },
        ),
    ]
