# Generated by Django 6.0.1 on 2026-01-10 18:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('preferred_llm', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI GPT'), ('anthropic', 'Anthropic Claude')], default='gemini', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('preferred_language', models.CharField(default='python', max_length=50)),
                ('preferred_framework', models.CharField(blank=True, max_length=100)),
                ('code_style', models.TextField(blank=True, help_text='Preferred coding style guidelines')),
                ('agent_autonomy_level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=3, help_text='1=Manual approval for everything, 5=Fully autonomous')),
                ('max_context_tokens', models.IntegerField(default=100000)),
                ('enable_memory', models.BooleanField(default=True)),
                ('enable_planning', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
            ],
        ),
    ]
