# Generated by Django 6.0.1 on 2026-01-10 20:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0003_agentexecution_agent_type'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, help_text='Title of the chat session', max_length=255)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Additional context for the chat session')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this chat session is currently active')),
                ('agent_session', models.ForeignKey(blank=True, help_text='Associated agent session if this chat is part of an agent workflow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='agents.agentsession')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('function', 'Function')], help_text='Role of the message sender', max_length=20)),
                ('content', models.TextField(help_text='Content of the message')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata like tool calls, function results, etc.')),
                ('tokens_used', models.IntegerField(blank=True, help_text='Number of tokens used for this message', null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', '-created_at'], name='chat_sessio_user_id_c65971_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['project', '-created_at'], name='chat_sessio_project_89e889_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['is_active', '-created_at'], name='chat_sessio_is_acti_304003_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='chat_messag_session_597c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['role', 'created_at'], name='chat_messag_role_b6a95d_idx'),
        ),
    ]
